# for some reason, <<: *base is not working
base: &base
  #adapter: em_postgresql
  host: localhost
  username: <%= ENV['DBUSER'] || ENV['USER'] || "root" %>
  password: <%= ENV['DBPASS'] || "" %>
  
development:
  adapter: em_postgresql
  post: 5432,
  pool: 10,
  host: localhost
  username: <%= ENV['DBUSER'] || ENV['USER'] || "root" %>
  password: <%= ENV['DBPASS'] || "" %>
  database: gmp_development
  wait_timeout: 2

production:
  adapter: em_postgresql
  post: 5432,
  pool: 10,
  host: localhost
  database: gmp_production

staging:
  adapter: em_postgresql
  post: 5432,
  pool: 10,
  host: localhost
  database: gmp_staging

test:
  adapter: em_postgresql
  post: 5432,
  pool: 10,
  host: localhost
  database: gmp_test
