# for some reason, <<: *base is not working

base: &base
  #adapter: em_postgresql
  host: localhost
  username: <%= ENV['DBUSER'] || ENV['USER'] || "zambosa" %>
  password: <%= ENV['DBPASS'] || "" %>
  
development:
  adapter: em_postgresql
  post: 5432,
  pool: 2,
  host: localhost
  username: <%= ENV['DBUSER'] || ENV['USER'] || "zambosa" %>
  password: <%= ENV['DBPASS'] || "" %>
  database: zambosa_dev
  wait_timeout: 2

production:
  <<: *base
  database: zambosa_prod

staging:
  <<: *base
  database: zambosa_staging

test:
  <<: *base
  database: zambosa_test
